error_log.settings:
  type: config_object
  label: 'Error Log settings'
  mapping:
    log_levels:
      type: mapping
      label: 'Log levels'
      mapping:
        level_0:
          type: boolean
          label: 'Emergency'
        level_1:
          type: boolean
          label: 'Alert'
        level_2:
          type: boolean
          label: 'Critical'
        level_3:
          type: boolean
          label: 'Error'
        level_4:
          type: boolean
          label: 'Warning'
        level_5:
          type: boolean
          label: 'Notice'
        level_6:
          type: boolean
          label: 'Info'
        level_7:
          type: boolean
          label: 'Debug'
    ignored_channels:
      type: sequence
      label: 'Log channels that should be ignored'
      sequence:
        type: string
        label: 'Log channel'
